version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout 
      - run: echo "hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout 
      - run: echo "world"

workflows:
  node-tests:
    jobs:
      - node/test
      - print-hello
      - print-world:
          requires: [print_hello]
